### ISSUE TITLE
Upload data from ESP to FTP server

### ISSUE THREAD

**Issue by salvq** [fa1ke5/ESP32_FTPServer_SD_MMC#1]
Hello @fa1ke5 just searching solution how to get data from SD card to FTP server (pc etc.).

I have data logging routines which save data into SD card (SDfat library) and would like to have 2 features:

1. ability to access SD card from client (local server / pc) and download / upload or delete files
2. ability to send files once per day to local FTP server (data backup)

Is this feasible with your library also upload data to FTP server ? 

Thanks

**Comment by fa1ke5** [comment]
This lib is only ftp read-write SERVER solution, write to another ftp not planning, sorry. You need ftp CLIENT for Esp32

**Comment by salvq** [comment]
@fa1ke5 got it.

Thanks anyway for quick response
