### ISSUE TITLE
MLSD command

### ISSUE THREAD

**Issue by BBBits** [fa1ke5/ESP32_FTPServer_SD_MMC#3]
Hi , just gave the example a test run.
couldn't drag'n drop a file into chrome , so connected with winscp
upload was fine at about 380kb/s
when I refreshed the DIR in winscp it was empty.
reloaded the ftp in chrome and the file listed ok.
added some folders with winscp but they show up as files in winscp .
winscp doesn't show the folder name "New Folder" perhaps because of the white space ?
here is some of the console.
28/06/20 18:29:06.741 Ftp server waiting for connection on port 21
28/06/20 18:29:06.747 Client connected!
28/06/20 18:29:06.801 USER esp32
28/06/20 18:29:06.856 PASS esp32
28/06/20 18:29:06.856 OK. Waiting for commands.
28/06/20 18:29:06.912 SYST
28/06/20 18:29:06.965 PWD
28/06/20 18:29:07.018 TYPE I
28/06/20 18:29:07.072 SIZE /
28/06/20 18:29:07.196 CWD /
28/06/20 18:29:07.253 PASV
28/06/20 18:29:07.253 Connection management set to passive
28/06/20 18:29:07.261 Data port set to 50009
28/06/20 18:29:07.316 LIST -l
28/06/20 18:29:07.324 ftpdataserver client....
28/06/20 18:29:07.324 File Name = babynames-gendered-2015.db
28/06/20 18:29:07.332 File Name = census2000names.db
28/06/20 18:29:07.332 File Name = mdr512.db
28/06/20 18:29:07.332 File Name = Data
28/06/20 18:29:07.373 QUIT
28/06/20 18:29:07.373  Disconnecting client
28/06/20 18:29:07.381 Ftp server waiting for connection on port 21
28/06/20 19:00:36.509 Client connected!
28/06/20 19:00:36.619 USER esp32
28/06/20 19:00:36.666 PASS esp32
28/06/20 19:00:36.666 OK. Waiting for commands.
28/06/20 19:00:36.822 SYST
28/06/20 19:00:36.916 FEAT
28/06/20 19:00:37.043 PWD
28/06/20 19:00:37.122 CWD /
28/06/20 19:00:37.231 PWD
28/06/20 19:00:37.325 TYPE A
28/06/20 19:00:37.434 PASV
28/06/20 19:00:37.434 Connection management set to passive
28/06/20 19:00:37.450 Data port set to 50009
28/06/20 19:00:37.543 MLSD
28/06/20 19:00:37.559 ftpdataserver client....
28/06/20 19:00:51.153 TYPE A
28/06/20 19:00:51.200 PASV
28/06/20 19:00:51.200 Connection management set to passive
28/06/20 19:00:51.216 Data port set to 50009
28/06/20 19:00:51.357 RETR Data
28/06/20 19:00:51.388 ftpdataserver client....
28/06/20 19:00:51.388 Sending Data
28/06/20 19:01:21.570 TYPE A
28/06/20 19:01:51.585 REST 0
28/06/20 19:02:21.476 PWD
28/06/20 19:02:51.477 TYPE I
28/06/20 19:02:51.618 TYPE A
28/06/20 19:02:51.665 PASV
28/06/20 19:02:51.665 Connection management set to passive
28/06/20 19:02:51.680 Data port set to 50009
28/06/20 19:02:51.727 MLSD
28/06/20 19:02:51.743 ftpdataserver client....
28/06/20 19:03:21.483 TYPE A
28/06/20 19:03:51.476 REST 0
28/06/20 19:04:21.493 TYPE I
28/06/20 19:04:51.492 TYPE A
28/06/20 19:04:52.214 TYPE A
28/06/20 19:04:52.261 PASV
28/06/20 19:04:52.261 Connection management set to passive
28/06/20 19:04:52.276 Data port set to 50009
28/06/20 19:04:52.417 MLSD
28/06/20 19:04:52.448 ftpdataserver client....
28/06/20 19:05:22.526 TYPE I
28/06/20 19:05:52.530 REST 0
28/06/20 19:06:22.524 TYPE I
28/06/20 19:06:52.537 TYPE I
28/06/20 19:06:52.749 TYPE A
28/06/20 19:06:52.800 PASV
28/06/20 19:06:52.800 Connection management set to passive
28/06/20 19:06:52.810 Data port set to 50009
28/06/20 19:06:52.850 MLSD
28/06/20 19:06:52.857 ftpdataserver client....
28/06/20 19:07:22.542 TYPE A
28/06/20 19:07:52.545 TYPE I
28/06/20 19:08:22.551 TYPE I
28/06/20 19:08:52.558 TYPE A
28/06/20 19:08:53.368 TYPE A
28/06/20 19:08:53.477 PASV
28/06/20 19:08:53.477 Connection management set to passive
28/06/20 19:08:53.493 Data port set to 50009
28/06/20 19:08:53.524 MLSD
28/06/20 19:08:53.539 ftpdataserver client....
28/06/20 19:08:53.649 CWD /
28/06/20 19:08:53.711 MKD New folder
28/06/20 19:08:53.852 TYPE A
28/06/20 19:08:53.914 PASV
28/06/20 19:08:53.914 Connection management set to passive
28/06/20 19:08:53.930 Data port set to 50009
28/06/20 19:08:53.989 MLSD
28/06/20 19:08:53.989 ftpdataserver client....
28/06/20 19:09:10.976 CWD /
28/06/20 19:09:11.085 MKD TestFolder
28/06/20 19:09:11.226 TYPE A
28/06/20 19:09:11.398 PASV
28/06/20 19:09:11.398 Connection management set to passive
28/06/20 19:09:11.398 Data port set to 50009
28/06/20 19:09:11.445 MLSD
28/06/20 19:09:11.445 ftpdataserver client....
28/06/20 19:09:41.501 REST 0
28/06/20 19:10:11.602 REST 0
28/06/20 19:10:41.533 REST 0
28/06/20 19:11:11.514 PWD
28/06/20 19:11:11.913 TYPE A
28/06/20 19:11:12.038 PASV
28/06/20 19:11:12.038 Connection management set to passive
28/06/20 19:11:12.054 Data port set to 50009
28/06/20 19:11:12.117 MLSD
28/06/20 19:11:12.132 ftpdataserver client....
28/06/20 19:11:42.547 TYPE I

WINSCP View (MLSD)
![winscp_MLSD](https://user-images.githubusercontent.com/6020029/85941088-cb841f80-b974-11ea-9481-d2b79e475751.JPG)

Chrome View  (LIST)
![chrome_LIST](https://user-images.githubusercontent.com/6020029/85941092-d17a0080-b974-11ea-8c64-84327890dba7.JPG)

Might get an opportunity to debug this so will keep ya posted.
Regards
Barry

**Comment by fa1ke5** [comment]
Hi Barry, as i know browser ftp client functionality dont support write on ftp by drag and drop function. Browsers ftp client is readonly.

**Comment by fa1ke5** [comment]
if you create folder in ftp cliet server create folder on sd too, you can see mkdir instruction in this code:
if( SD_MMC.mkdir( path )){
            client.println( "257 \"" + String(parameters) + "\" created");
            }
for stable work in wincsp try setup connection parameters "passive mode" e.t.c

**Comment by fa1ke5** [comment]
or try totalcomander ftp client....

**Comment by BBBits** [comment]
Hi,
the problem is actually with the response format of the MLSD command.
perhaps you haven't experienced the problem because your clients only use the LIST command
the correct response was actually commented out so I changed it and all is ok now.
 **//  data.println(fn);
data.println( "Type=dir;Size=" + fs + ";"+"modify=20000101000000;" +" " + fn);
          } else {
//   data.println( fs + " " + fn);
data.println( "Type=file;Size=" + fs + ";"+"modify=20000101160656;" +" " + fn);**

Winscp now displays correct dir structure
![winscp_MLSD_Correct](https://user-images.githubusercontent.com/6020029/85972162-46a40f00-ba23-11ea-9cce-515910d5758a.JPG)

**Comment by Zuoqiu-Yingyi** [comment]
Thank you for sharing this project.
However, some shortcomings were found during my analysis of the source code of this project. 

[Line 125](https://github.com/fa1ke5/ESP32_FTPServer_SD_MMC/blob/29074c3baa091b0a15a8c9479fadaa1a9a122a3e/ESP32_FTPServer_SD/ESP32FtpServer.cpp#L125)
else if (!client.connected() || !client)
Methods "client.connected()" and methods "client::bool()" have the same effect

[Line 338](
https://github.com/fa1ke5/ESP32_FTPServer_SD_MMC/blob/29074c3baa091b0a15a8c9479fadaa1a9a122a3e/ESP32_FTPServer_SD/ESP32FtpServer.cpp#L338)
char * p = strchr( parameters, ',' );
If parameters is empty, function strchr( const char* str, int ch ) will return NULL
If p = NULL, "++p" will throw an exception

[Line 567](
https://github.com/fa1ke5/ESP32_FTPServer_SD_MMC/blob/29074c3baa091b0a15a8c9479fadaa1a9a122a3e/ESP32_FTPServer_SD/ESP32FtpServer.cpp#L567)
There is a invalid branch, which conflicts with [Line565](https://github.com/fa1ke5/ESP32_FTPServer_SD_MMC/blob/29074c3baa091b0a15a8c9479fadaa1a9a122a3e/ESP32_FTPServer_SD/ESP32FtpServer.cpp#L565))


[Line 402](https://github.com/fa1ke5/ESP32_FTPServer_SD_MMC/blob/29074c3baa091b0a15a8c9479fadaa1a9a122a3e/ESP32_FTPServer_SD/ESP32FtpServer.cpp#L402)
[Line 404](https://github.com/fa1ke5/ESP32_FTPServer_SD_MMC/blob/29074c3baa091b0a15a8c9479fadaa1a9a122a3e/ESP32_FTPServer_SD/ESP32FtpServer.cpp#L404)
There is an if-else-if construct which can replaced by "if (haveParameter() && makePath(path))" 
The latter is safer
Same for [Line 560](https://github.com/fa1ke5/ESP32_FTPServer_SD_MMC/blob/29074c3baa091b0a15a8c9479fadaa1a9a122a3e/ESP32_FTPServer_SD/ESP32FtpServer.cpp#L560), [Line 590](https://github.com/fa1ke5/ESP32_FTPServer_SD_MMC/blob/29074c3baa091b0a15a8c9479fadaa1a9a122a3e/ESP32_FTPServer_SD/ESP32FtpServer.cpp#L590), [Line 691](https://github.com/fa1ke5/ESP32_FTPServer_SD_MMC/blob/29074c3baa091b0a15a8c9479fadaa1a9a122a3e/ESP32_FTPServer_SD/ESP32FtpServer.cpp#L691), [Line 742](https://github.com/fa1ke5/ESP32_FTPServer_SD_MMC/blob/29074c3baa091b0a15a8c9479fadaa1a9a122a3e/ESP32_FTPServer_SD/ESP32FtpServer.cpp#L742)

**Comment by jruizcoll** [comment]
Thanks BBBits for pointing this issue. Your solution worked for me on OLIMEX ESP32-PoE and SD card, using FileZilla FTP client Passive mode

**Comment by jajito** [comment]
Same problem here.
Now it's solved.
Thanks!
It was driving me crazy!

**Comment by bhupiister** [comment]
> Hi, the problem is actually with the response format of the MLSD command. perhaps you haven't experienced the problem because your clients only use the LIST command the correct response was actually commented out so I changed it and all is ok now. **
// data.println(fn); 
data.println( "Type=dir;Size=" + fs + ";"+"modify=20000101000000;" +" " + fn); 
} else 
{ 
// data.println( fs + " " + fn); 
data.println( "Type=file;Size=" + fs + ";"+"modify=20000101160656;" +" " + fn);**
> 
> Winscp now displays correct dir structure ![winscp_MLSD_Correct](https://user-

I had to figure this out myself, i wish i had seen your comment before and saved few hours.
By the way it still shows as below and the very reason why FileZilla is not able to list the files and directory.
```
data.println(fn);
data.println( fs + " " + fn);
```
Who so ever is watching this comment, uncomment below lines
```
data.println( "Type=dir;Size=" + fs + ";"+"modify=20000101000000;" +" " + fn); 
data.println( "Type=file;Size=" + fs + ";"+"modify=20000101160656;" +" " + fn);**
```
At last, thankyou to everyone who made efforts to make and maintain this library.

**Comment by fa1ke5** [comment]
Внес изменения в мастер ветку, теперь используются
data.println( "Type=dir;Size=" + fs + ";"+"modify=20000101000000;" +" " + fn); 
data.println( "Type=file;Size=" + fs + ";"+"modify=20000101160656;" +" " + fn);**
Проблему закрываю, спасибо всем участникам за их помощь
