### ISSUE TITLE
Error in main code 

### ISSUE THREAD

**Issue by govinda3402** [fa1ke5/ESP32_FTPServer_SD_MMC#8]
error in wifi.begin line as:invalid conversion from 'const char*' to 'char*' [-fpermissive]

**Comment by fa1ke5** [comment]
Эта ошибка не должна влиять на успешную компиляцию. Поскольку только const char гарантирует наличие нуллтерминатора, а в свою очередь вызываемая функция по нему определяет длину, компилятор отмечает это как ВОЗМОЖНУЮ ошибку. Если вы передаёте функции переменную в качестве параметра она в принципе не может иметь значение const. Если ваш код не собирается, то причина не в этом
